### ISSUE TITLE
Feature request: store dictionary info in Markdown file

### ISSUE THREAD

**Issue by dimonster** [openstenoproject/stenodict#20]
It would be nice to write about dictionaries in straight Markdown, rather than Markdown inside a JSON file, where `dict_name_info.md` would contain only Markdown and no JSON.

I imagined this using inline Markdown from `dict_name_info.json` if the `how` key is present, and otherwise loading the Markdown from `dict_name_info.md`. 

I'd like to share more dictionaries, but am finding the escaped, inline Markdown tedious.

**Comment by morinted** [comment]
Maybe I should change over to Jekyll? I've been considering the virtues of it lately…

**Comment by dimonster** [comment]
Jekyll is ace, though I think this fix would be smaller and see results quicker than converting the site. If stenodict keeps growing after that you might decide you want a back end after all, then another architectural change would be necessary. In the spirit of small iterative changes and getting new features in front of people faster, I'd delay the switch to jekyll. 

But I'm biased because I'm interested in seeing this feature sooner. 

What virtues were you thinking of?

**Comment by morinted** [comment]
Mainly search engine indexing, non-JavaScript support, and Markdown-everywhere.

**Comment by dimonster** [comment]
Yeah worthy pursuits. Would pre-rendered html with react help?

**Comment by morinted** [comment]
You know, I didn't even think of a webpack static site generator. That's a
great idea.

**Comment by morinted** [comment]
The static site generator looks like a pain. I'll look into Jekyll, I've been meaning to learn it and Liquid anyway.

**Comment by morinted** [comment]
So the new dictionaries would be completely self-contained, metadata-wise, in a Markdown file. Here's a preview of the mainpage I've been working on (in Jekyll):

![screen shot 2016-03-18 at 7 04 56 pm](https://cloud.githubusercontent.com/assets/5840970/13894275/721aeac2-ed3c-11e5-94b0-329e2912f59c.png)

**Comment by dimonster** [comment]
Neat. How are the URLs looking now?

**Comment by dimonster** [comment]
I'm more familiar with Jekyll than React (or ES6) so I'm happy to contribute if you want to throw work my way.

**Comment by morinted** [comment]
Hey @dimonster, check out http://www.openstenoproject.org/stenodict/ ! I think it's a good start to making dictionaries easier to work with.
