### ISSUE TITLE
Add movement keys dictionary

### ISSUE THREAD

**Issue by morinted** [openstenoproject/stenodict#5]
Add Ted's way of handling movement keys with and without shift.

**Comment by morinted** [comment]
@Achim63, I saw your dictionaries in the Google Group. How would you like to contribute your movement keys dictionary with a write up? It would be super awesome to have some of your dictionaries for public release date.

**Comment by Achim63** [comment]
I don't know if we could incorporate my dictionary entries into a release, since most of them are rather Mac oriented (and I had to change some to adapt them to my German keyboard layout, so they won't work on a US one, e.g. the keys to switch to the next app window).
On top of being OS dependent, it's a matter of preference - some want the arrows on the right, some on the left. And it's dependent on the main dictionary: I selected my strokes to give as few conflicts with Magnum as possible.
I have a full set of Cmd+a, Cmd+b ... Cmd+z and Cmd+Alt+(a..z) and all the F-keys up to F12 (alone and with different modifier keys).
I might save those as something like "OSX_special_keys.json" and push them here - maybe you could just "cherrypick" those that would be useful to all.

**Comment by morinted** [comment]
This isn't the Plover repo, this is a repo for a dictionary-sharing platform I'm working on. You'll be able to tag your dictionary as Mac-specific and provide a description. See the example (barebones) up at http://www.tedmor.in/stenodict/

**Comment by Achim63** [comment]
Where am I supposed to put it, then? I'm just starting out using SourceTree for my first steps into git, but it's all still pretty confusing to me.

**Comment by morinted** [comment]
You can just fill in the details I need here, if you'd like, but if you want to try out Git, here's how:

Fork the repository on GitHub, clone your fork, then open it in SourceTree. Switch to branch `gh-pages` (default is `master`).

You must edit one file and create two for each dictionary you want to add. Let's say that I'm creating a dictionary named `poop_dictionary.json`. Its contents are `{"PAOP": "poop"}` (for example's sake).

## File you edit

First step: add it to the list of dictionaries. This is found in the `gh-pages` branch under the files `/dictionaries.json`. In that file, you should see a JSON tree with a key "dictionaries" (starts at line 20).
You would add your own, something like this:

```JSON
, "dictionaries":
  { "unicode_arrows":
    { "name": "Arrows"
[... this being another entry ...]
    }
  , "poop_dictionary":
    { "name": "Poop!"
    , "filename": "poop_dictionary"
    , "what": "This dictionary is about poop"
    , "tags":
      [ 0
      , 9
      ]
    , "formats":
      [ 0
      ]
    }
[...more stuff]
```
The tags are taken from the top of the file. In this case 0 and 9 means "words" and "meta". The format 0 means json. You can technically upload both a json and rtf version and the site will handle it. The "what" tag is your short tagline that will be what users see about the dictionary before clicking through to its page. "name" is the title of the dictionary.

## File you create 1: info about your dictionary

An important file. This file is stored in `gh-pages/dictionaries/` as `filename_info.json` where filename is the name you gave above (in this example, `dictionaries/poop_dictionary_info.json`. It contains 3 tags: "filename" (same as above, it's just a verification step; `poop_dictionary` in our case), "why" and "how". "Why" is your chance to explain why users might want to use this dictionary. Keep it to one paragraph. It's a Markdown string, so you can use all that kind of formatting as you with. "how" is where you explain what strokes map to what. It's an array, and each string in it is a Markdown paragraph. See `unicode_arrow_info.json` for an example.

## File you create 2: the dictionary

Easiest part: just place your dictionary (either `poop_dictionary.json` or `poop_dictionary.rtf`) in `/dictionaries/`.

Commit the change, push it to your GitHub fork, submit a pull request. I can give you feedback and help with any step if you need it.

**Of course, you don't have to do any of this! If you just give me the dictionary, tell me the title, what it is (one-liner), why to use it, and how to use it, I can make these files.** You'll have to give me all these details for each dictionary you want to submit. Again, you can check the example I made with the "unicode_arrows" dictionary on www.tedmor.in/stenodict (at the moment)

**Comment by morinted** [comment]
I'll make this change for yours and @dimonster's movement key ideas, if that's all right with both of you. I'll make sure to note the author correctly on each.

@Achim63 and @dimonster, are you okay with me posting what you wrote about movement keys on the Google Groups?

**Comment by Achim63** [comment]
Sorry I didn't have time yet to look further into this. Feel free to use the stroke suggestions I mentioned in the Google group, no copyright on them ;-)

**Comment by dimonster** [comment]
Sure

**Comment by dimonster** [comment]
@morinted, would you please share your programming dictionaries? I was just about to start creating briefs for markdown and spotted yours. I imagine you already have lots of excellent briefs for other languages? Even before you've annotated them, I'd appreciate a look to help get me started.

**Comment by morinted** [comment]
I just have one big "custom.json" at the moment. Not sure how useful that
would be :P

**Comment by dimonster** [comment]
Completely useful!

**Comment by morinted** [comment]
@dimonster Here you go, this is my personal dictionary… If you have any questions I can probably answer them. https://drive.google.com/file/d/0B_4v0_ER8UlweEdGQk5UcEFxbVE/view?usp=sharing

**Comment by dimonster** [comment]
:O Thank you!

**Comment by morinted** [comment]
@Achim63 check it out http://www.openstenoproject.org/stenodict/#/dictionary/left_mac_movement

**Comment by Achim63** [comment]
Thanks! By now I changed the Ctrl and Ctrl+Alt combinations, since I need the Ctrl+arrow more frequently to switch spaces in OSX. So *RLGTS is just Ctrl now, *RPBLT is Ctrl+Alt.

"P*RPBLT": "{^}{#Control_L(Alt_L(Up))}{^}",
"W*RPBLT": "{^}{#Control_L(Alt_L(Down))}{^}",
"K*RPBLT": "{^}{#Control_L(Alt_L(Left))}{^}",
"R*RPBLT": "{^}{#Control_L(Alt_L(Right))}{^}",
"P*RLGTS": "{^}{#Control_L(Up)}{^}",
"W*RLGTS": "{^}{#Control_L(Down)}{^}",
"K*RLGTS": "{^}{#Control_L(Left)}{^}",
"R*RLGTS": "{^}{#Control_L(Right)}{^}",

**Comment by morinted** [comment]
Curious, @Achim63, what are your settings in OS X for Keyboard >> Keyboard >> Modifier Keys... ? Are they at my default?

<img width="407" alt="screen shot 2015-11-07 at 4 10 19 pm" src="https://cloud.githubusercontent.com/assets/5840970/11017342/11fe622a-856a-11e5-97a3-e1a4d8dd0ee9.png">

**Comment by Achim63** [comment]
Yes, as I use a standard Apple bluetooth keyboard right now. I just reset the system preferences for the keyboard shortcuts of Mission Control - ctrl+left/right arrow are indeed the defaults to switch spaces. Ctrl+up arrow calls Mission Control, Ctrl+down arrow the app window overview.
At work, where I have a Cherry keyboard in use, I have option and command switched.

**Comment by morinted** [comment]
Ah, cool. I will be updating your dictionary with your revision tonight, hopefully closing this issue :smirk_cat:

**Comment by morinted** [comment]
@dimonster I've added your movement dictionary now, too, here: http://www.openstenoproject.org/stenodict/#/dictionary/movement_di

Mine is up there as well. The list is ever growing!

**Comment by dimonster** [comment]
@morinted, cool. I'm excited to see this grow! Fantastic work.

There seems to be a stray entry for "and and and" in that dictionary...?

Looking at your dictionary, what does {\*-|} do? As in `"HRA*PBD": "{*-|}{^land}",`?

**Comment by morinted** [comment]
In the new versions of Plover, it capitalizes the previous word. I use that
to make words like "Awesomeland".

Yes, I'll have to remove the and and and. I make silly strokes to make
Plover sort the dictionary :p

**Comment by dimonster** [comment]
Hah! Nice one.

I saw somewhere that you were working on adding Markdown documentation for the next Plover, could you (or I) add these new Plover commands?

**Comment by morinted** [comment]
Mmm, yes.. Still trying to decide on how to do that. A gitbook at
www.openstenoproject.org/plover ?

**Comment by dimonster** [comment]
I've never used GitBook, but sounds like a great option. Do it!

(My only hesitation would be about MarkDown + heavy use of asterisks in steno content, but looks like GitBook handles that fine if you use code blocks.)
