### ISSUE TITLE
Mirabai's vim dictionary

### ISSUE THREAD

**Issue by morinted** [openstenoproject/stenodict#7]
Hey @stenoknight, will you be able to contribute your vim-bindings strokes at some point? You can wait until I'm nearing release and have more dictionaries if you are not sure of the format.

**Comment by stenoknight** [comment]
Happy to! Though it's really just a handful of commands, most of them captioning-specific; search, substitute, write to path, save silently, Google search word under cursor (requires plugin), delete to end of document, turn off blink, turn off spellcheck, reformat document (small font), reformat document (big font). That sort of thing. Might not have general applicability. On the whole, I tend to just use generic Vim commands in steno (w, b, cw, dd, etc) most of the time. I only make specific definitions for more complex nested tasks.

**Comment by morinted** [comment]
I see your points. Perhaps it'll serve at least as a good example as to the
power of steno for users who are trying to figure out how to build their
own special dictionaries.
